version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  docker: circleci/docker@0.5.20
  
workflows:
  build_and_publish_docker_image:
    jobs:
      - docker/publish:
          image: ${CIRCLE_PROJECT_USERNAME}/${DOCKER_PROJECT_REPONAME}
