version: 2.1 # Use version 2.1 to enable orb usage.

orbs:
  docker: circleci/docker@0.5.20
  
workflows:
  commit:
    jobs:
      - build_and_push

jobs:
  build_and_push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - run: ls
      - checkout
      - run: ls
      - docker/check
      - docker/build:
          image: ${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME}
      - docker/push:
          image: ${DOCKER_LOGIN}/${CIRCLE_PROJECT_REPONAME}
          
